### ISSUE TITLE
1.1_BasicLandingPage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/userStories#1]
## Value Proposition

*As a* user,

*I need* to be able to see the landing page and

*to be able to* see 6 different tattoo ideas

----------

## Description

The Landing Page shows a random collection of tattoo-ideas.
[
<img width="272" alt="Bildschirmfoto 2022-12-10 um 11 08 34" src="https://user-images.githubusercontent.com/115539625/206851249-885bc586-8cdf-4141-be9c-5ce7ae5ab33e.png">
](url)

---------------------

## Acceptance Criteria

- [ ] Header is visible
- [ ] Main shows 6 different tattoos (hardcoded)
- [ ] Footer is visible

-----------------

## Tasks

- [ ] create new next.js project
- [ ] add repo in github
- [ ] write header, main, footer components
- [ ] style components
- [ ] header has a burgermenu (no functional)
- [ ] main has filter buttons (not functional) and 6 picturecards

**Comment by esrefbozkurt** [comment]
Looks good, good structure, not sure, if the buttons with no function should be displayed already. Excited that you choose the tattoo idea looking forward to the end product!

**Comment by onebarloop** [comment]
> Looks good, good structure, not sure, if the buttons with no function should be displayed already. Excited that you choose the tattoo idea looking forward to the end product!

Good point. I will consider that.

**Comment by julialoeschel** [comment]
Hey. 
Sehr gute US, 
bist auf die Filterfunktion , die nicht funtioniert (bitte rausnehmen) habe ich nichts auzusetzen

die Filterbuttons iplementierst du dann mit der Userstory über Filter :) 

:octocat:

**Comment by onebarloop** [comment]
> 

Will do! Danke Julia!
