### ISSUE TITLE
1.2_ArtistObject

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/userStories#2]
## Value Proposition

*As a*  user, i want to be be able to visit the artists page

----------

## Description

When a tattoo Idea is clicked, the user should be forwarded to the artists page

---------------------

## Acceptance Criteria

- [ ] tattoo Ideas are Links to the artist page
- [ ] artist page shows artist details

-----------------

## Tasks

- [ ]  crate Artist Object.
- [ ] create template for artist page -> dynamic link via artist name
- [ ] page should render artist name, location and all tattoos -ideas of the artist
