### ISSUE TITLE
1.3_FilterMainpage

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/userStories#4]
## Value Proposition

*As a* user

*to be able to* see a list of Artists on the mainpage.
*i need to be able to* switch between regular view and artist view

----------

## Description

<img width="325" alt="Bildschirmfoto 2022-12-11 um 16 24 45" src="https://user-images.githubusercontent.com/115539625/206912493-aa03d5b6-0c47-4e45-9d57-bf9daa6dd926.png">

---------------------

## Acceptance Criteria

- [ ] Mainpage renders all Artist Objects with information (name and location) and one tattoo
- [ ] Button to switch between regular view (random tattoos) and artist view works

-----------------

## Tasks

- [ ] Change artist-objects, so they have a prop "id". nanoid is used for random id generation. This will later be handled by MongoDB
- [ ] write a component to render a list of all artists.
- [ ] style this component
- [ ] implement on mainpage with conditional rendering - mainview : artistview. Store the value in state.
- [ ] write a button component to switch between views
- [ ] style the button component
