### ISSUE TITLE
1.4_LikeButton

### ISSUE THREAD

**Issue by onebarloop** [onebarloop/userStories#5]
## Value Proposition

As a user, I want to be able to bookmark (like) specific artists.

----------

## Description

![Bildschirmfoto 2022-12-12 um 11 17 06](https://user-images.githubusercontent.com/115539625/207020894-4eb6da6a-ab35-4499-963e-d1e293c66b4e.png)

---------------------

## Acceptance Criteria

- [ ] Like button toggles status and changes color
- [ ] bookmark filter-button works and main only renders bookmarked artists

-----------------

## Tasks

- [ ] create new state: array of the id's of the bookmarked cards
- [ ] add button component to artist card. button should add or remove the id from the state-array 
- [ ] add condition in styled components to switch between button-colors 
- [ ] create filter button
- [ ] add option "bookmarked" to the viewState array
- [ ] implement conditional rendering of bookmarked items on mainpage
